name: Linter
on:
  push:
    branches:
      - workflow-test
env:
  node-version: 16.10.0

jobs:
  linter-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation linter et lancement
        run: |
          npm i -g eslint
          eslint --init
          eslint ./backend/routes/ ./backend/server.js --fix 


