name: TestUnitaires-Backend
on:
  push:
    branches:
      - develop

env:
  node-version: 16.10.0

jobs:
  postgres-job:

    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ProjetIntegration
          POSTGRES_PASSWORD: 19992003i
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
  
 test-backend:
    runs-on: ubuntu-latest
    needs: [postgres-job]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
      - name: npm install
        working-directory: ../backend
        run: |
          npm install
      - name: run test
        working-directory: ../backend
        run: |
          npm run test
