name: Backend
on:
  push:
    branches:
      - handleError

jobs:
  test-backend:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ProjetIntegration
          POSTGRES_PASSWORD: '123'
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run migrations
        run: psql -f ./db/fichier.sql postgresql://postgres:123@localhost:5432/ProjetIntegration
      - name: Installation des dépendences de node
        working-directory: ./backend
        run: |
          npm install
      - name: run test
        working-directory: ./backend
        env: 
          DATABASE_HOST: localhost
          DATABASE: ProjetIntegration
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: '123'
          DATABASE_PORT: 5432
        run: |
          npm run test
