name: TestUnitaires-Backend
on:
  push:
    branches:
      - develop

jobs:
  postgres:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: "ProjetIntegration"
          POSTGRES_PASSWORD: "19992003i"
          POSTGRES_PORT: 5432
          POSTGRES_USER: "postgres"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Installation des dépendences de node
        working-directory: ./backend
        run: |
          npm install
      - name: run test
        working-directory: ./backend
        env:
          DBURL: "postgresql://postgres:19992003i@localhost:5432/ProjetIntegration"
        run: |
          npm run test