name: ReconnaissanceFaciale
on:
  push:
    branches:
      - Security
env:
  node-version: 16.10.0

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installation python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Installation des dependances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



